config/routes.rb
Classtrack4::Application.routes.draw do
  devise_for :administrators
  mount RailsAdmin::Engine => '/rails_admin', :as => 'rails_admin'

  resources :students
  resources :subscriptions, only: :destroy
  resources :semesters
  resources :courses, only: :index

  root to: "students#new"
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :remember_me
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :semester
  has_many :subscriptions, dependent: :destroy
  has_many :students, through: :subscriptions

  validates_presence_of :semester

  before_update :send_mail_if_just_opened


  def attributes
    {id: self.id, name: self.name}
  end

  def name
    "#{code}-#{section} / #{semester.name} / #{title} / #{instructors} / #{time}"
  end

  def code_section
    "#{code}-#{section}"
  end

  protected

  def send_mail_if_just_opened
    if (enrolled_changed? || cap_changed?) && (enrolled_was >= cap_was) && (enrolled < cap)
      students.each do |student|
        CourseMailer.course_opened(self, student).deliver
      end
    end
  end

end

app/models/semester.rb
class Semester < ActiveRecord::Base
  has_many :courses, dependent: :destroy
  has_many :subscriptions, through: :courses

  attr_accessible :name, :starting, :ending, :xml_url
  validates_presence_of :name, :starting, :ending, :xml_url
  validates_url :xml_url, if: proc{ !Rails.env.test? }


  is_sluggable :to_label, history: false, sync: false

  def active?
    starting < Time.now && ending > Time.now
  end

  def self.active
    where("starting < ? and ending > ?", Time.now, Time.now)
  end

  def to_label
    name
  end


end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :subscriptions, dependent: :destroy, inverse_of: :student
  has_many :courses, through: :subscriptions

  attr_accessible :email, :course_tokens

  validates_presence_of :random_string, :email
  validates_format_of :email,
    with: /^[a-zA-Z0-9\_\-]+[a-zA-Z0-9\.\_\-]*@([a-zA-Z0-9\_\-]+\.)+([a-zA-Z]{2,4})$/

  validate :course_tokens_provided, on: :create
  # this should also do it on update, but it could break other things
  # as of right now, user can go to home page, put in email w/ no courses, and get no error

  before_validation :generate_random_string, on: :create

  after_save :send_account_information, if: proc{ |s| s.changed? }

  attr_reader :course_tokens

  def course_tokens=(ids)
    self.course_ids = (self.course_ids + ids.split(',')).uniq
    changed_attributes[:course_tokens] = nil
  end

  def current_courses
    courses.where(semester: self.semester)
  end

  def confirm_random_string(string)
    random_string == string
  end

  protected

  def course_tokens_provided
    if course_ids.empty?
      errors.add(:course_tokens, "can't be blank")
    end
  end

  def generate_random_string
    self.random_string = SecureRandom.hex(10)
  end

  def send_account_information
    StudentMailer.account_information(self).deliver
  end


end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :student, inverse_of: :subscriptions
  belongs_to :course

  validates_presence_of :student, inverse_of: :subscriptions
  validates_uniqueness_of :student_id, scope: :course_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_student

  protected

  def access_denied(message = nil)
    flash[:notice] = message || "Access Denied"
    redirect_to "/"
    return false
  end

  def confirm_random_string
    if params[:s]
      session[:s] = params[:s]
    end
    access_denied unless student.confirm_random_string(session[:s])
  end

  def current_student
    @current_student ||= if (id = flash[:student_id])
      flash.delete(:student_id)
      Student.find_by_id(id)
    elsif session[:s]
      Student.find_by_random_string(session[:s])
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  inherit_resources
  actions :index
  respond_to :json

  protected

  def collection
    @courses ||= Course.where(semester_id: Semester.active).where("title ilike ? or code ilike ? or instructors ilike ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
  end
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  before_filter :authenticate_administrator!
  inherit_resources
  defaults finder: :find_using_slug
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  inherit_resources
  actions :all, except: [:edit]

  before_filter :confirm_random_string, only: [:show]

  def create
    if !build_resource.new_record?
      update
    else
      create! do |success,failure|
        success.html do
          flash[:student_id] = resource.id
          redirect_to root_path
        end
        failure.html do
          render 'new'
        end
      end
    end
  end

  def update
    update! do |success,failure|
      success.html do
        flash[:notice] = t("flash.students.update.notice")
        flash[:student_id] = resource.id
        redirect_to root_path
      end
      failure.html do
        flash[:alert] = t("flash.students.update.alert")
        render 'new'
      end
    end
  end

  protected

  def build_resource
    @student ||= Student.find_or_initialize_by_email(params[:student])
  end

  def student
    resource
  end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :confirm_random_string, only: :destroy

  inherit_resources
  actions :destroy

  def destroy
    destroy! do |format|
      format.html { redirect_to student_path(student) }
    end
  end

  protected

  def interpolation_options
    { code: resource.course.code }
  end

  def student
    resource.student
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    "#{controller.controller_name} #{controller.controller_name}-#{controller.action_name}"
  end

  def bootstrap_flash_key(key)
    new_key = case key
    when :alert
      'alert-error'
    when :notice
      'alert-success'
    end
    new_key
  end
end

app/views/layouts/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <% unless key == :student_id %>
      <div class="alert <%= bootstrap_flash_key(key) %>"><%=h value %></div>
    <% end %>
  <% end -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />

    <title>Classtrack: We're watching your classes</title>

    <meta name="description" content="<%= yield(:description) || "PROJECT DESCRIPTION" %>" />
    <meta name="keywords" content="<%= yield(:keywords) || "PROJECT KEYWORDS" %>" />
    <%= csrf_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag "application" %>

    <%= yield :extra_header %>
  </head>
  <body class="<%= body_class %>">
    <div class="container container-fixed">

      <div class="content">
        <div class="page-header">
          <a href="/"><h1>ClassTrack <small>Relax. We're watching your classes.</small></h1></a>
        </div>
        <div class="row">
          <% if yield(:sidebar).present? %>
            <div class="span5 main-column">
          <% else %>
            <div class="span9">
          <% end %>

          <%= render :partial => 'layouts/flashes' -%>

          <%= yield %>
          </div>

          <% if yield(:sidebar).present? %>
            <div class="span3 right-column">
              <%= yield :sidebar %>
            </div>
          <% end %>


        </div>
      </div>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= yield :extra_footer %>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-20518270-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
    <% if current_student %>
      <script>
        var intercomSettings = {
          app_id: 'gjrih5t6',
          email: '<%== current_student[:email] %>', // TODO: User's e-mail address
          created_at: <%== current_student[:created_at].to_i %> // TODO: User's sign-up date, Unix timestamp
        };

        (function() {
          function async_load() {
            var s = document.createElement('script');
            s.type = 'text/javascript'; s.async = true;
            s.src = 'https://api.intercom.io/api/js/library.js';
            var x = document.getElementsByTagName('script')[0];
            x.parentNode.insertBefore(s, x);
          }
          if (window.attachEvent) {
            window.attachEvent('onload', async_load);
          } else {
            window.addEventListener('load', async_load, false);
          }
        })();
      </script>
    <% end %>
  </body>
</html>

app/views/semesters/_form.html.erb
<%= simple_form_for @semester do |f| %>
  <%= f.input :name %>
  <%= f.input :starting %>
  <%= f.input :ending %>
  <%= f.input :xml_url %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', collection_path %>

app/views/semesters/edit.html.erb
<%= render 'form' %>

app/views/semesters/index.html.erb
<h2>Admin: Semesters</h2>
<%= button_to "Sign out", destroy_administrator_session_path, method: :delete %>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Last Updated</th>
    <th>Active</th>
    <th>Ending</th>
    <th></th>
    <th></th>
  </tr>
  <% @semesters.order('ending asc').each do |semester| %>
  <tr>
    <td><%= semester.name %></td>
    <td><%= distance_of_time_in_words_to_now(semester.last_enrollment_scraped_at, true) rescue "Never" %> ago</td>
    <td><%= semester.active? %></td>
    <td><%= semester.ending %></td>
    <td><%= link_to 'Show', resource_path(semester) %></td>
    <td><%= link_to 'Edit', edit_resource_path(semester) %></td>
  </tr>
  <% end %>
</table>
<%= link_to 'New Semester', new_semester_path %>

app/views/semesters/new.html.erb
<%= render 'form' %>

app/views/semesters/show.html.erb
<h1><%= @semester.name %></h1>
<dl>
  <dt>Name</dt>
  <dd><%= @semester.name %></dd>

  <dt>Starting date</dt>
  <dd><%= @semester.starting %></dd>

  <dt>Ending date</dt>
  <dd><%= @semester.ending %></dd>

  <dt>Course information source</dt>
  <dd><%= link_to @semester.xml_url, @semester.xml_url %></dd>

  <dt>Last information update</dt>
  <dd><%= distance_of_time_in_words_to_now(@semester.last_information_scraped_at) rescue "Never" %></dd>

  <dt>Last enrollment update</dt>
  <dd><%= distance_of_time_in_words_to_now(@semester.last_enrollment_scraped_at, true) rescue "Never" %></dd>
</dl>

<%= link_to 'Back', collection_path %>

app/views/students/new.html.erb
<h2>Start tracking courses</h2>
<%= simple_form_for @student, html: { class: 'form-vertical' } do |f| %>
  <%= f.input :email, required: false %>
  <%= f.input :course_tokens, required: false, label: "Courses" %>
  <%= f.submit "Start tracking", class: "btn btn-custom btn-large", style: "margin-top: 10px" %>
<% end %>

<%= content_for :sidebar do %>
  <h3>Quick Hits</h3>
  <p>A course tracking system that makes registering for full college classes a breeze. </p>
  <p>Tell us your favorite courses and we'll watch them for you. </p>
  <p>Next time one of your favorites opens, we'll shoot you an email.</p>
  <br />
  <p>Created by <a href="http://jmondo.com/">John Gesimondo ‘12</a></p>
<% end %>

app/views/students/show.html.erb
<table>
  <tr>
    <th>Course</th>
    <th></th>
  </tr>
  <% @student.subscriptions.each do |sub| %>
  <% course = sub.course %>
  <tr>
    <td><%= course.name %></td>
    <td><%= button_to "Stop tracking", subscription_path(sub), method: :delete %></td>
  </tr>
  <% end %>

</table>

<p>You can always track more courses by revisiting the <%= link_to "home page", root_path %></p>